In [12]:
#import glints as g
import jobstreet as j
import techinasia as t
import pandas as pd
import datetime as dt
from selenium import webdriver

driver = webdriver.Safari()
program=['FSJS','PMKT','UIUX','FTDS']
#jobs = ['Backend Developer','Frontend Developer','Mobile Developer','Web Developer']
jobs = ['Digital Marketing']
#jobs = ['Junior UI UX Designer','Associate Product Designer','UI Designer','UX Designer','Product Designer','Interaction Designer','UX Researcher']
#jobs = ['Data Analyst','Data Scientist','Data Engineer','Machine Learning','Artificial Intelligence','Business Intelligence']
#dat_g = g.scraper(jobs,driver)
dat_j = j.scraper(jobs)
dat_t = t.scraper(jobs,driver)
driver.close()

In [11]:
#df = pd.concat([dat_g,dat_j])
df = pd.concat([df_j,dat_t])
df.reset_index(drop=True).to_excel(f'data_{program}_{dt.datetime.now().date()}.xlsx',index=False)

In [1]:
#import glints as g
import jobstreet as j
import techinasia as t
import pandas as pd
import datetime as dt
from selenium import webdriver

data = pd.DataFrame()
try:
    driver = webdriver.Safari()
except:
    driver.close()
    driver = webdriver.Safari()
    
program=['FTDS']#['FSJS','PMKT','UIUX','FTDS']
jobs = [#['Backend Developer','Frontend Developer','Mobile Developer','Web Developer'],['Digital Marketing'],
        #['Junior UI UX Designer','Associate Product Designer','UI Designer','UX Designer','Product Designer','Interaction Designer','UX Researcher'],
        ['Data Analyst','Data Scientist','Data Engineer','Machine Learning','Artificial Intelligence','Business Intelligence']]
for i,p in enumerate(program):
    #dat_g = g.scraper(jobs[i],driver)
    dat_j = j.scraper(jobs[i])
    dat_t = t.scraper(jobs[i],driver)
    df = pd.concat([dat_j,dat_t])
    data = pd.concat([data,df])
    df.reset_index(drop=True).to_excel(f'data_{p}_{dt.datetime.now().date()}.xlsx',index=False)
driver.close()

In [4]:
df

,Portal,Last Update,Job Title,Company,Location,Description,Job Type,URL,Salary,Category,Required Skills,get_data,Experience
0,Jobstreet,2024-06-15,credit marketing officer (cmo) - malang,None,None,Mencari aplikasi/menjual pembiayaan kepada cal...,None,https://www.jobstreet.co.id/id/job/77282193?ty...,NaN,NaN,NaN,NaN,NaN
1,Jobstreet,2024-06-15,finance analyst & cost control supervisor (kon...,None,None,Kualifikasi:Pendidikan terakhir minimal S1 jur...,None,https://www.jobstreet.co.id/id/job/77281805?ty...,NaN,NaN,NaN,NaN,NaN
2,Jobstreet,2024-06-15,property business analyst,None,None,The Property Business Analyst will play a key ...,None,https://www.jobstreet.co.id/id/job/77281729?ty...,NaN,NaN,NaN,NaN,NaN
3,Jobstreet,2024-06-15,it project development analyst,None,None,Deskripsi Pekerjaan :Melakukan koordinasi bers...,None,https://www.jobstreet.co.id/id/job/77280579?ty...,NaN,NaN,NaN,NaN,NaN
4,Jobstreet,2024-06-15,system analyst,None,None,Job Summary :Analyze whole system's requiremen...,None,https://www.jobstreet.co.id/id/job/77280465?ty...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,Techinasia,24 Jun 2024,IT Business Analyst Sr. Specialist (Arya Noble),Dealls,"Jakarta, Indonesia",N/A,Full-time,https://www.techinasia.com/jobs/1ee4f2a8-d8cf-...,,Data & Analytics,[],[],Nan
8,Techinasia,29 May 2024,Revenue Lead,Hangry,"Jakarta, Indonesia",Job description & requirements Job Description...,Full-time,https://www.techinasia.com/jobs/ce23ecc6-6e30-...,,Sales & Business Development,"[Business Analysis, Business Development, Busi...","[Sales & Business Development, Full-time, Less...",Less than 1 year
9,Techinasia,10 Jul 2024,Product Owner - Banking Industry (Full Onsite),SIGMATECH,"Jakarta, Indonesia",Job description & requirements Memahami SME (s...,Contract,https://www.techinasia.com/jobs/2c44198a-93ad-...,"IDR 9,000,000 â€“ 12,000,000",Project & Product Management,"[Product Development, Product Management, Prod...","[Project & Product Management, Contract, 1 to ...",1 to 4 years
10,Techinasia,8 Jul 2024,Data Warehouse Engineer - Full Onsite,SIGMATECH,"Jakarta, Indonesia",Job description & requirements Full Onsite - B...,Contract,https://www.techinasia.com/jobs/d6203601-257c-...,"IDR 9,000,000 â€“ 12,000,000",Data & Analytics,"[Data Analysis, Data Warehouse, Big Data, Data...","[Data & Analytics, Contract, 1 to 4 years, 1]",1 to 4 years
11,Techinasia,22 May 2024,Application Engineer,AccuSentry,"Jakarta, Indonesia",Job description & requirements We are looking ...,Full-time,https://www.techinasia.com/jobs/4913eb60-d8f4-...,"IDR 8,000,000 â€“ 12,000,000",Hardware & Embedded Systems,"[Mechanical Engineering, Business Development,...","[Hardware & Embedded Systems, Full-time, Less ...",Less than 1 year